import { getSupportedTypes } from './cucumber-expression.js';
import type { GeneratedSnippet, SnippetOptions } from './snippet-generator.js';

export class SnippetBuilder {
  /**
   * Generate TypeScript step definition code
   */
  public static generateTypeScriptCode(
    keyword: string, 
    pattern: string, 
    params: string[],
    hasParameters: boolean
  ): string {
    const supportedTypes = getSupportedTypes().map(t => t.slice(1, -1)); // Remove { }
    const handlerName = this.generateHandlerName(keyword, pattern);
    const paramsType = hasParameters ? ', params: Record<string, any>' : '';
    
    let code = `import type { Step, TestContext } from '../types/index.js';\n\n`;
    code += `// Step definition for: ${keyword} ${pattern}\n`;
    code += `export const ${handlerName} = async (step: Step, context: TestContext${paramsType}) => {\n`;
    code += `  // TODO: Implement your step logic here\n`;
    code += `  \n`;
    
    if (hasParameters) {
      code += `  // Extracted parameters:\n`;
      for (const param of params) {
        code += `  // const ${param} = params['${param}'];\n`;
      }
      code += `  \n`;
    }
    
    code += `  // Example:\n`;
    code += `  // console.log('Step: ${keyword} ${pattern}');\n`;
    code += `  // const value = context.variables['yourVariable'];\n`;
    code += `  // await context.httpClient.request({ method: 'GET', url: 'https://api.example.com' + value });\n`;
    code += `};\n`;
    code += `\n`;
    code += `// Register this step:\n`;
    code += `// {\n`;
    code += `//   '${keyword} ${pattern}': ${handlerName},\n`;
    code += `// }\n`;
    code += `\n`;
    code += `// Supported parameter types: ${supportedTypes.join(', ')}\n`;
    
    return code;
  }

  /**
   * Generate a handler function name from the step pattern
   */
  public static generateHandlerName(keyword: string, pattern: string): string {
    let name = keyword.toLowerCase();
    const words = pattern.replace(/[{}]/g, '').split(/[\s_-]+/);
    for (const word of words) {
      if (word) {
        name += word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      }
    }
    if (!/^[a-zA-Z]/.test(name)) {
      name = 'handle' + name;
    }
    return name;
  }

  /**
   * Generate a complete step definitions file
   */
  public static generateStepDefinitionsFile(steps: GeneratedSnippet[]): string {
    let code = `/**\n * Hop Step Definitions\n * Auto-generated by Hop Framework\n * \n * Edit this file to implement your step logic\n */\n\n`;
    code += `import type { Step, TestContext } from '../types/index.js';\n\n`;

    for (const step of steps) {
      code += `// ============================================\n`;
      code += `// Step: ${step.pattern}\n`;
      code += `// ============================================\n`;
      code += step.code;
      code += `\n`;
    }

    code += `// ============================================\n`;
    code += `// Export all step definitions\n`;
    code += `// ============================================\n`;
    code += `const stepDefinitions = {\n`;
    
    for (const step of steps) {
      const parts = step.pattern.split(' ');
      const handlerName = this.generateHandlerName(parts[0], step.pattern.slice(parts[0].length + 1));
      code += `  '${step.pattern}': ${handlerName},\n`;
    }
    
    code += `};\n\n`;
    code += `export default stepDefinitions;\n`;
    
    return code;
  }

  /**
   * Generate a summary message for undefined steps
   */
  public static generateUndefinedStepMessage(steps: SnippetOptions[]): string {
    const supportedTypes = getSupportedTypes().map(t => t.slice(1, -1));
    
    let message = `\n`;
    message += `╔════════════════════════════════════════════════════════════╗\n`;
    message += `║          Undefined Step Definitions Found                 ║\n`;
    message += `╚════════════════════════════════════════════════════════════╝\n\n`;
    message += `The following steps have no matching step definition:\n\n`;
    
    for (const step of steps) {
      message += `  ${step.keyword} ${step.stepText}\n`;
    }
    
    message += `\n`;
    message += `To fix this, create a step definition file at './steps/custom-steps.ts':\n\n`;
    message += `  1. Create the file with your step implementations\n`;
    message += `  2. Export a default object with step patterns as keys\n`;
    message += `  3. Run tests again\n\n`;
    
    message += `Supported Parameter Types:\n`;
    for (const type of supportedTypes) {
      message += `  - {${type}}\n`;
    }
    
    message += `\nExample:\n`;
    message += `  Given user with id {int} exists\n`;
    message += `  When I update user {string} with data {string}\n`;
    message += `  Then response status should be {int}\n`;
    
    return message;
  }
}
